### ISSUE TITLE
"Specify fields to track" proposal

### ISSUE THREAD

**Issue by aalebedev** [romgar/django-dirtyfields#102]
Hi! I think, it will be a good option - to specify a set of fields to track.

```
class MyDirtyFieldsMixin(dirtyfields.DirtyFieldsMixin):
    fields_to_track = ['name',]

class MyModel(models.Model, MyDirtyFieldsMixin):
    name = models.CharField(max_length=20)
    # 100 of other fields here
```

It can help to get performance improvements (I performed a some tests in my project). There is a such option in django-model-utils: https://django-model-utils.readthedocs.io/en/latest/utilities.html#tracking-specific-fields
If this idea is good, I can try to write a patch.

**Comment by romgar** [comment]
Hi @aalebedev! Sounds definitely a nice idea!
