### ISSUE TITLE
Remove useless code (support < Dj 1.8 dropped)

### ISSUE THREAD

**Issue by hsmett** [romgar/django-dirtyfields#106]
in django-dirtyfields/tests/test_save_fields.py:
@unittest.skipIf(django.VERSION < (1, 5), "Django 1.4 doesn't support update_fields param on save()")

Those lines aren't usefull anymore :)

**Comment by romgar** [comment]
You are right @hsmett, thanks for reporting!

**Comment by romgar** [comment]
Fixed in #107
