### ISSUE TITLE
reset_state fails when combining update_fields and FIELDS_TO_CHECK

### ISSUE THREAD

**Issue by bparker98** [romgar/django-dirtyfields#113]
When you use FIELDS_TO_CHECK on a model and then save it using update_fields, and update_fields contains a field not in FIELDS_TO_CHECK you get a KeyError because it's trying to pull a field from new_state in reset_state() that is not there.

Quick and dirty repro case:

    class TestModelWithSpecifiedFields(DirtyFieldsMixin, models.Model):
        boolean1 = models.BooleanField(default=True)
        boolean2 = models.BooleanField(default=True)
        FIELDS_TO_CHECK = ['boolean1']

    tm = TestModelWithSpecifiedFields.objects.create()

    tm.boolean1 = False
    tm.boolean2 = False
    
    # This is causing the KeyError
    tm.save(update_fields=["boolean2"])

I'll have a PR up with a fix soon.

**Comment by romgar** [comment]
Thanks for the reporting and the incoming PR @bparker98 !!

**Comment by MounirMesselmeni** [comment]
@romgar When do you plan to release this please?

**Comment by romgar** [comment]
I will create a new release in the next days.

**Comment by romgar** [comment]
@MounirMesselmeni `1.3.1` released :tada: 

Sorry for the delay...
