### ISSUE TITLE
KeyError when using F object and update_fields

### ISSUE THREAD

**Issue by MounirMesselmeni** [romgar/django-dirtyfields#118]
I'm getting a KeyError when trying to update a single field with an F object

```python
model.my_field = F('my_field') + 1
model.save(update_fields=['my_field'])
# will raise a KeyError
model.save()
# Will work
```
`_as_dict` method will not contain `my_field` when I'm using F objects

**Comment by romgar** [comment]
Thanks for reporting! Will have a look!

**Comment by 4word** [comment]
I am still seeing this. 

My workaround right now is, whenever I am using an F object, I refresh the instance from the database  and select it for update right before saving and then just use `save()` without the update fields to make sure I am saving the latest version of all the fields.
