### ISSUE TITLE
Performance hit in a django view

### ISSUE THREAD

**Issue by OrDuan** [romgar/django-dirtyfields#132]
We saw a performance hit on one of our stats pages where we query around 800 rows of data each one of them has around 15-20 columns, some of them query json fields and some arrays. 

We discovered that the issue is in django-dirtyfields, which we use a lot, but not in this specific view. 

![screenshot from 2018-09-05 21-19-42](https://user-images.githubusercontent.com/5006049/45116250-d0059580-b15a-11e8-8bda-91bbe0dc78e1.png)

There is no easy way to turn off the checks, we `patch`ed the `_as_dict` method as a workaround.

Would be great if we could have a way to turn the dirtyfields off in specific cases where its not needed and not just globally with `FIELDS_TO_CHECK`.

**Comment by romgar** [comment]
Thanks for your reporting @OrDuan !

What is the interface you would like to have to turn them off?

**Comment by OrDuan** [comment]
We had 3 ideas:
1. Decorator
2. Context manager
3. QuerySet method

The first two are similar in implementation and usage.
The QuerySet option might be our favorite(and probably easiest to implement without mocking[which we tried but it doesn't work well with threads because of the shared memory]), so something like this:

`User.objects.filter(email="test@example.com").no_dirtyfields().first()` /
`User.objects.no_dirtyfields().filter(email="test@example.com").first()` /
`User.objects.no_dirtyfields(include_relations=True).filter(email="test@example.com").first()` 

I'm not sure about my naming, but this is the general idea :) what do you think?

**Comment by YAmikep** [comment]
Hi @romgar 

I work with @OrDuan 
I created a PR to show our current solution if that can help: https://github.com/romgar/django-dirtyfields/pull/134

IMO, it's quite hacky as it requires to override some core django components so if you have a better solution, feel free to ignore all of part of it.

Thanks

**Comment by romgar** [comment]
Thanks for the PR and sorry for the delay... Will have a look in the next days!!

**Comment by yj7** [comment]
Any update on this?

**Comment by LincolnPuzey** [comment]
@OrDuan @YAmikep I think a better solution would be to use a Django Proxy Model.

From the [docs](https://docs.djangoproject.com/en/dev/topics/db/models/#proxy-models):

> Sometimes, however, you only want to change the Python behavior of a model – perhaps to change the default manager, or add a new method. This is what proxy model inheritance is for

For example you can have your regular Model:

```python
class User(models.Model):
    ...
```

Use this class when you don't want dirty fields to be tracked.

Then have a proxy Model which includes `DirtyFieldsMixin`

```python
class UserWithDirty(DirtyFieldsMixin, User):
    class Meta:
        proxy = True
```

Use this class when you _do_ want dirtyfields to be tracked.

Both model classes will operate on the same database table and have exactly the same fields, the proxy Model will just have different behavior in Python - i.e. it will track dirty fields.

This is much nicer as is doesn't involve overriding or patching any Django components - and I think this is the type of situation that Proxy Models are meant to be used for.

**Comment by LincolnPuzey** [comment]
Since no-one objected to my suggestion above, I went ahead and documented it in #193. Going to close this issue now.
