### ISSUE TITLE
get_dirty_fields after M2M.clear() problem

### ISSUE THREAD

**Issue by korviinn** [romgar/django-dirtyfields#137]
Hi, 
I'm using django-dirtyfields==1.3.0
And find such a problem:
I've got a model - Order with two fields:
- Vehicle - M2M field
- start_datetime - Datetime field

I try to update start_datetime and delete all vehicles in my Order.
In the result I need to print in logs of usual fields(no FK and M2M), with their new values
In my function I got such code:

> order.pickup_datetime = pickup_datetime
> logger.debug(order.is_dirty())
> logger.debug(order.get_dirty_fields())
> 
> order.vehicle.clear()
> 
> logger.debug(order.is_dirty())
> logger.debug(order.get_dirty_fields())
> 
> order.save()

When I look in my logs file I see the following thing:

DEBUG

>  True
> DEBUG {'pickup_datetime': datetime.datetime(2018, 12, 7, 15, 5)}
> DEBUG False
> DEBUG {}

As you see before .clear() everything is ok, but then something goes wrong.
And if I override order.save() method with self.get_dirty_fields() in it - I also got empty dict in the result.

What am I doing wrong?

**Comment by romgar** [comment]
Hi @korviinn !

Are you setting the `ENABLE_M2M_CHECK` parameter to `True`?
If that's the case, your `Order` model also starts listening to the `m2m_changed` Django signals (triggered in this case by your `clear()` call, which resets the dirty field tracking and explains why your model instance is in a clean state afterwards.

**Comment by romgar** [comment]
Closing the issue for inactivity. Please feel free to open again if needed.
