### ISSUE TITLE
Handle enum comparison

### ISSUE THREAD

**Issue by cvlong** [romgar/django-dirtyfields#139]
I'm trying to track the changes for a text field where the choices are defined by an Enum class. For example:

```
class TestEnums(enum.Enum):
    one = 'One'
    two = 'Two'

class EnumFieldModel(DirtyFieldsMixin, models.Model):
    enum_field = models.TextField(choices=[(choice.name, choice.value) for choice in TestEnums])
```

Though this [line](https://github.com/romgar/django-dirtyfields/blob/develop/src/dirtyfields/dirtyfields.py#L71) is casting the instance to a string, so the original and current values aren't able to be compared properly.

```python
getattr(self, 'enum_field')  # <TestEnums.two: 'Two'>
type(getattr(self, 'enum_field'))  # <enum 'TestEnums'>

self._original_state.get('enum_field')  # 'TestEnums.one'
type(self._original_state.get('enum_field'))  # <class 'str'>
```

I'd like to propose a small change to handle Enums more consistently. I'll be happy to take this on and submit a PR if this sounds ok.

**Comment by romgar** [comment]
Yes please! Thanks for that!
Associated PR: #140

**Comment by dhaval-mehta** [comment]
@romgar Can you merge #140?

I think DRF and Django have removed support for python2 and changed minimum supported Python version to 3.4

Those who are using Django 1.11 LTS can use older versions without enum support.

**Comment by LincolnPuzey** [comment]
@cvlong In your example the list of `choices` you provide for the `enum_field`  evaluates to 

```python
[('one', 'One'), ('two', 'Two')]
```

Which is just a list of tuples of strings. So Django and django-dirtyfields knows nothing about the `TestEnums` Enum used to initially define the choices, and `enum_field` is just a regular `TextField` with choices.

So django-dirtyfields should not need to do anything special to handle your use case.
