### ISSUE TITLE
publish new version ?

### ISSUE THREAD

**Issue by mathieu-gillot** [romgar/django-dirtyfields#150]
Hi, and thx for the good work on this lib

would it be possible to publish a new 1.4 version to get all new code merged since 1.3 ?

i'm very interested in getting fix done in commit fda116e09e1843f61cc67e1bd4c9635d707948fd for instance

**Comment by lubo** [comment]
@romgar We're interested as well.

**Comment by romgar** [comment]
Yes, on it! Sorry, last months have been a bit intense for me.

**Comment by romgar** [comment]
Version `1.4` released. Sorry for the delay. I will be more responsive in the future!!
