### ISSUE TITLE
Django 3.1 + Python 3.8 support?

### ISSUE THREAD

**Issue by virogenesis** [romgar/django-dirtyfields#153]
Just wondering if anyone tested if this is safe to use on a Django 3.1 and python 3.8, I know it's not covered by tox, but  if would be interested in if anyone saw any issues.

**Comment by ron8mcr** [comment]
@virogenesis I've met problem with using `dirtyfields` for `FileField`. Previous Django version used simpler implementation of `__getstate__`, and 3.1 add `instance` to state, so `deepcopy` also copies instance, which is much slower and consume more memory.

Django changes: https://github.com/django/django/commit/f600e3fad6e92d9fe1ad8b351dc8446415f24345
deepcopy: https://github.com/romgar/django-dirtyfields/blob/develop/src/dirtyfields/dirtyfields.py#L95

**Comment by LincolnPuzey** [comment]
@virogenesis Django 3.1 and python 3.8 is now covered by tox. I'll close this issue.
