### ISSUE TITLE
Looking for new contributors

### ISSUE THREAD

**Issue by romgar** [romgar/django-dirtyfields#155]
Hi everyone,

As I have been quite unresponsive in the last weeks/months and I don't have much time to take care of this project anymore, that would be great if someone was interested in handling this project.
I would gladly help / support anyone wanting to give a hand in reviewing PRs, pushing releases, adding more features, etc.
That's an interesting experience for someone who never handled an open-source project before, and slowly wants to start doing so (as there are not too many issues/PRs to tackle, and the project in itself is quite simple).
Anyone interested, please answer in this thread and we will make that happen :-)

**Comment by LincolnPuzey** [comment]
Hi @romgar,

I am happy to spend some time maintaining the project, in particular bug fixes and keeping python/django support up-to-date.

**Comment by romgar** [comment]
Great to hear @LincolnPuzey !
I will give you access to the repository.

Some information about this repository:
- I'm currently following [this flow](https://nvie.com/posts/a-successful-git-branching-model/) for branching/releasing, `develop` is therefore the development branch (all PRs should go to this branch), while `master` is the release branch,
- All PRs should have proper tests covering it.

To release a new version:
- Update the `setup.py` file with the new version number (I currently follow [semver](https://semver.org/)),
- Update the `ChangeLog.rst` with all the new changes introduced by the release,
- If some [documentation ](https://django-dirtyfields.readthedocs.io/en/develop/)update is needed, please reach me out, and also check if the `README.rst` file should be updated as well,
- When all the changes are done, you can release a new version automatically on PyPi by creating a new tag and pushing it in the `master` branch. The version appearing on PyPi will be the one defined in the `setup.py` file (but please keep the tag name consistent with the version).

In case of any issue/question, please feel free to reach me on [twitter](https://twitter.com/rgarrigues).

**Comment by LincolnPuzey** [comment]
Thanks @romgar
