### ISSUE TITLE
Foreign key change is not detected

### ISSUE THREAD

**Issue by mmzeynalli** [romgar/django-dirtyfields#219]
**Describe the bug**
When I change foreign key field, it is not detected by mixin

**To Reproduce**
```python
class Status(models.Model):
    name = models.CharField(max_length=32, unique=True)

class Package(DirtyFieldsMixin, models.Model):  # Solution 4
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)
    shipment_cost = models.DecimalField(max_digits=6, decimal_places=2)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    status = models.ForeignKey(Status, on_delete=models.CASCADE)

# In the shell
>>> from cache_fields.models import *
>>> package = Package.objects.get()
>>> package.is_dirty()
False
>>> package.status_id = 5
>>> package.is_dirty()  # The same if I change the above line to package.status = Status.objects,get(id=5)
False
```

**Expected behavior**
After change, is_dirty should return True

**Actual Behavior**
It returns false

**Environment (please complete the following information):**
 - OS: Windows 10
 - Python version: 3.10.1
 - Django version: 4.2.7
 - django-dirtyfields version: 1.9.2

**Additional context**

**Comment by LincolnPuzey** [comment]
See https://django-dirtyfields.readthedocs.io/en/stable/advanced.html#checking-foreign-key-fields
