### ISSUE TITLE
Log user and timestamp

### ISSUE THREAD

**Issue by davidmir** [romgar/django-dirtyfields#61]
Hi,

It's possible to save the user that modified the field and the timestamp?

Thanks

**Comment by romgar** [comment]
Hi @davidmir,
I don't think it's a good idea to save user informations, as models are independent from the request cycle (where you get the user).
The timestamp would be more feasible, but would only keep the latest update.
If you want to track updates on your models, have a look at `django-audit-log` (https://github.com/Atomidata/django-audit-log), which keeps an history of your objects and also contains this user information.
