### ISSUE TITLE
_as_dict_m2m make a lot more extra queries

### ISSUE THREAD

**Issue by MounirMesselmeni** [romgar/django-dirtyfields#73]
Hi,

_as_dict_m2m make extra queries even when I prefetch_related m2m fields.

My example is the following, `A` have a FK to `B` and `B` have a m2m to `C`
B is the only model using DirtyFieldMixin. Doing ```A.objects.all().prefetch_related('b__c')``` will not avoid extra queries.
Is there a way to avoid this or to disable m2m checks and initialisation?

**Comment by romgar** [comment]
Hi @MounirMesselmeni !

I will have a look.
On the worst case, I can add an option to `DirtyFieldMixin` to allow you to disable it if not needed.

**Comment by romgar** [comment]
At the end, the option to deactivate it is the only thing I could see to make it work. But then it means that you won't be able to check m2m fields diff.
I have just created a PR for that.

**Comment by MounirMesselmeni** [comment]
Hi, thanks for your reply. I would say yes, I prefer this to hundreds of extra queries on many places (API, pages, ...) I would suggest to disable it by default to warn users about possible extra queries and why not find a better way to prefetch this m2m relations to reduce the queries count.

**Comment by romgar** [comment]
That's probably a better idea to turn it off by default, I agree.

About the prefetch, feel free to propose a solution if you think about one :-)
