### ISSUE TITLE
Use of `Field.rel` raises warnings from Django 1.9+

### ISSUE THREAD

**Issue by 9thbit** [romgar/django-dirtyfields#80]
The use of `field.rel` on https://github.com/romgar/django-dirtyfields/blob/develop/src/dirtyfields/dirtyfields.py#L43 causes warnings to be raised because of its deprecation from Django 1.9+

See: https://docs.djangoproject.com/en/1.10/releases/1.9/#field-rel-changes

**Comment by romgar** [comment]
Thanks @9thbit for the report! I will fix it!

**Comment by romgar** [comment]
It will be released in version `1.2.1`.

**Comment by 9thbit** [comment]
Fantastic, thanks very much @romgar!
