### ISSUE TITLE
post_save get_dirty_fields dict has fewer keys

### ISSUE THREAD

**Issue by imaia** [romgar/django-dirtyfields#86]
Hello. Today, during tests, after upgrading to django dirtyfields 1.2, I noticed that get_dirty_fields returns a different dictionary during pre_save and post_save if I'm creating a new object.

In post_save, it will only show fields that were modifed during pre_save. In pre_save, it will show all fields, if it is a new model instance. Why is that? Is that expected?

**Comment by romgar** [comment]
Hi @imaia! Can you copy/paste some code examples to demonstrate your issue?
It is indeed expected to have all fields to be dirty in a new model instance in a `pre_save` signal. Being "dirty" means that the value on the model is different than the database one, which is always true when you don't have saved it yet.
As `django-dirtyfields` is relying on `post_save` signal to update its internal state, depending on your code, different behaviours can be seen.

**Comment by romgar** [comment]
Closing this one. Please reopen it if needed @imaia.
