### ISSUE TITLE
It does not work if pk is specified.

### ISSUE THREAD

**Issue by prajnamort** [romgar/django-dirtyfields#88]
It does not work if pk is specified.
`if not self.pk` shouldn't be used to judge the state.

**Comment by prajnamort** [comment]
@romgar 
I'm not sure whether the `if self.pk` statement in `_as_dict_m2m` shares the same problem since I didn't use m2m_check.

**Comment by romgar** [comment]
It's not that easy to detect if a model has already been saved in the db without extra queries.

Giving your example, we definitely can't rely on `id/pk`, but I don't see right now a way to distinguish:
- data coming from the database,
- data that we initialize with a specific `id/pk` value.

When the instances are returned from a Django query, they are initialized on the same way as we could have done manually, and they shouldn't be dirty...

**Comment by romgar** [comment]
For now, I don't find any solution for this particular issue with current logic. If somebody has an idea, I'm interested.

At the meantime, I will update the documentation with this special case.
